[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Branch specific settings
[context.master.processing]
  skip_processing = false
[context.master.processing.css]
  bundle = true
  minify = true